spring.application.name=mallapi
# view resolver
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp
# oracle jdbc \uc124\uc815
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=malldbuser
spring.datasource.password=malldbuser
# jpa \uc124\uc815
spring.jpa.database=oracle
# SQL\uc744 Oracle \ubb38\ubc95\uc5d0 \ub9de\uac8c \uc0dd\uc131\ud558\ub294 \uc124\uc815
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# \uae30\uc874 \uc2dc\ud000\uc2a4 \ubc29\uc2dd\uacfc \ucda9\ub3cc \ubc29\uc9c0
spring.jpa.properties.hibernate.id.new_generator_mappings=false
# jpa\uac00 \ud14c\uc774\ube14\uc744 \uc790\ub3d9 \uc0dd\uc131/\uc218\uc815
spring.jpa.hibernate.ddl-auto=update
# SQL\uc744 \uc608\uc058\uac8c \uc904\ubc14\uafc8\ud574\uc11c \ucd9c\ub825
spring.jpa.properties.hibernate.format_sql=true
# jpa\uac00 DDL \uc0dd\uc131 \ud5c8\uc6a9
spring.jpa.generate-ddl=true
# \uc2e4\ud589\ub418\ub294 SQL\uc744 \ucf58\uc194\uc5d0 \ucd9c\ub825
spring.jpa.show-sql=true
# \ub85c\uadf8 \ucd9c\ub825 \ubc94\uc704 \uc124\uc815
logging.level.org.hibernate=info
## \uc790\ub8cc\uc5c5\ub85c\ub4dc \uc0ac\uc774\uc988
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.max-file-size=10MB
## \ub0b4\ubd80\ud3f4\ub354 (\uc774\ubbf8\uc9c0\ud30c\uc77c\uc800\uc7a5)
com.kh.upload.path=upload